sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: your_username  # 替换为您的MySQL用户名
    password: your_password  # 替换为您的MySQL密码

  alioss:
    endpoint: 
    access-key-id:
    access-key-secret: 
    bucket-name:
  redis:
    host: localhost
    port: 6379
    database: 10

  wechat:
    appid:
    secret: 
    mchid:
    mchSerialNo:
    privateKeyFilePath:
    apiV3Key:
    weChatPayCertFilePath:
    notifyUrl:
    refundNotifyUrl:
