sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  
    host: localhost 
    port: 3306  
    database: sky_take_out  # 数据库名称
    username: your_username  # 替换为您的MySQL用户名
    password: your_password  # 替换为您的MySQL密码

  alioss:
    endpoint:  # 阿里云OSS的终端节点
    access-key-id:  # 阿里云OSS的访问密钥ID
    access-key-secret:  # 阿里云OSS的访问密钥Secret
    bucket-name:  # 阿里云OSS的存储桶名称

  redis:
    host: localhost 
    port: 6379  
    database: 10  

  wechat:
    appid:  # 微信公众平台的应用ID
    secret:  # 微信公众平台的应用密钥
    mchid:  # 微信支付商户号
    mchSerialNo:  # 微信支付商户证书序列号
    privateKeyFilePath:  # 微信支付商户私钥文件路径
    apiV3Key:  # 微信支付API v3密钥
    weChatPayCertFilePath:  # 微信支付证书文件路径
    notifyUrl:  # 微信支付通知URL
    refundNotifyUrl:  # 微信支付退款通知URL
